config:
  target: "https://bvn83uv9g8.execute-api.us-east-1.amazonaws.com/prod"
  plugins:
    expect: {}
  phases:
    - duration: 60
      arrivalRate: 10
      name: warm up phase
    - duration: 120
      arrivalRate: 5
      rampTo: 100
      name: Ramp up load
    - duration: 600
      arrivalRate: 100
      name: Sustained load