config:
  target: 'http://localhost:3000'
  plugins:
    expect: {}
  phases:
    - duration: 30
      arrivalRate: 10
      name: "npm package validation"
  processor: "../utils/test-runner.js"
  variables:
    testEnvironment: "npm-package"
    testRunId: "{{ $randomString() }}"
